---
name: Check

on:
  workflow_dispatch:
  pull_request:

jobs:   
  check:    
    runs-on: ubuntu-22.04           
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Lint with golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: Run Go tests
      run: go test -v ./...

    - name: Run GoReleaser check
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: build --skip-validate 
